# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/tyoajanseuranta-node

    steps:
      - checkout
      - run: npm install
      - run: npm run prod

  deploy:
    machine: true
    working_directory: ~/tyoajanseuranta-node
    steps:
      - checkout
      - run: git fetch
      - run: git checkout master
      - run: git pull
      - run: npm install
      - run: npm run prod

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build