# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    machine: true
    working_directory: ~/tyoajanseuranta-node

    steps:
      - run: git fetch
      - run: git pull
      - run: npm install
      - run: npm run prod